# Generated by Django 3.2.4 on 2021-08-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('fno', models.AutoField(primary_key=True, serialize=False)),
                ('Form_Title', models.CharField(max_length=700)),
                ('Admin_Name', models.CharField(max_length=50)),
                ('Admin_Username', models.CharField(default='', max_length=1000)),
                ('Timestamp_Created', models.CharField(max_length=50)),
                ('Timestamp_Sheduled', models.CharField(max_length=50)),
                ('Timestamp_End', models.CharField(max_length=50)),
                ('Qsns', models.TextField(default='')),
                ('Correct_Ans', models.TextField(default='')),
                ('ResponseJson', models.TextField(default='')),
                ('Extras', models.TextField(default='')),
            ],
        ),
    ]
