# Generated by Django 3.2.4 on 2021-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Form_app', '0002_rename_post_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='Extra_info',
            field=models.TextField(default=''),
        ),
    ]
