# Generated by Django 3.2.4 on 2021-08-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Form_app', '0003_forms_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='Admin_Name',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='forms',
            name='Timestamp_Created',
            field=models.CharField(max_length=505),
        ),
        migrations.AlterField(
            model_name='forms',
            name='Timestamp_End',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='forms',
            name='Timestamp_Sheduled',
            field=models.CharField(max_length=505),
        ),
    ]
