# Generated by Django 3.2.4 on 2021-08-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Form_app', '0004_auto_20210827_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='Extra_info',
            new_name='Disc',
        ),
    ]
