# Generated by Django 3.2.4 on 2021-08-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Form_app', '0008_auto_20210827_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Res',
        ),
    ]
